# Use a Node.js base image
FROM node:18

# create working directories
RUN mkdir -p /app

# Install app dependencies
COPY api_gateway/* /app

# Set the working directory to /app and build the app
WORKDIR /app
RUN npm install

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start the app
CMD ["npm", "start"]
